"""empty message

Revision ID: 24895a0c8104
Revises: f95c84c6a0f5
Create Date: 2024-10-29 12:50:21.837819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24895a0c8104'
down_revision = 'f95c84c6a0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
